/**
 * Autogenerated class that displays board. Panel will be extracted from "initialize" class.
 * @author Dominic, @Mihail
 */
package guiClasses;

import javax.swing.JFrame;
import java.awt.Point;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JLabel;



public class CatanWindow {

	final int SCALE = 30;
	private JFrame frame;
	
	public CatanWindow(ArrayList<Point> referencePoints) {
		initialize(referencePoints);
	}

	/**
	 * Initialize the contents of the frame.
	 */

	private void initialize(ArrayList<Point> referencePoints) {
		frame = new JFrame();
		frame.setResizable(false);
		frame.setBounds(100, 100, 750, 650);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().setLayout(null);
		
		JPanel panel = new JPanel();
		panel.setBounds(0, 0, 600, 600);
		frame.getContentPane().add(panel);
		panel.setLayout(null);
		//TODO resize image icons in CatanWindow
		
		for(Point point : referencePoints){
			ImageIcon icon = new ImageIcon("PanelImages/Test.png");
			JLabel lblHex = new JLabel("", icon, JLabel.CENTER);
			int x = (int)point.getX();
			int y = (int)point.getY();
			lblHex.setBounds(x*SCALE, y*SCALE, SCALE*2, SCALE*3);
			panel.add(lblHex);
		}
		frame.setVisible(true);
	}
}
